{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "example.%s" .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: engineering-prod
        url: https://2.4.6.8
  template:
    metadata:
      name: {{ printf "%s" .name | quote }}
    spec:
      project: default
      source:
        path: {{ .path | default .name | quote }}
        repoURL: {{ $config.spec.source.repoURL }}
        targetRevision: {{ $config.spec.source.targetRevision }}
        {{- with .tool }}
        {{- . | toYaml | nindent 4 }}
        {{- end }}
      destination:
        server: {{ $config.spec.destination.server | quote }}
        namespace: {{ .namespace | default .name | quote }}
---
{{ end -}}
